### ISSUE TITLE
NuGet Package - PDB Files

### ISSUE THREAD

**Issue by steji113** [zeux/pugixml#110]
The current NuGet package only supplies the static libraries but does not include .pdb files to aid in debugging. I am proposing to include the PDBs in the NuGet package and uploading it alongside the current version to assist developers troubleshoot issues.

Thanks!

**Comment by zeux** [comment]
(copying info from the PR for completeness)

Due to some usability issues with NuGet debug symbols in .PDB, pugixml uses /Z7 (old debug information style) to put debug info into the object files. Linker then will move the debug info to the main .pdb file for the executable pugixml is linked to.

This should work for VS2015 as it is, but may not be set up for VS2013.
