### ISSUE TITLE
How to move node

### ISSUE THREAD

**Issue by xfcanyue** [zeux/pugixml#123]
Hello. How can i do move node from one document to anther document. With the same memory address, it is not copy node.

Thanks very much.

**Comment by zeux** [comment]
You can not move a node between documents and preserve the memory address. What you can do is:

- Copy the node and remove the source of the copy
- Work in a single document (put every document as a subtree of the merged document, using xml_node::append_buffer) and use move (e.g. xml_node::append_move)

This restriction exists because nodes are allocated in pages, and document manages node lifetime using pages - this makes it impossible to transplant a node to another document without transplanting the entire page (which may have many other nodes or attributes that you did not want to move).
