### ISSUE TITLE
Register with pkg-config

### ISSUE THREAD

**Issue by legoktm** [zeux/pugixml#128]
Hi! It would be helpful if libpugixml was registered with pkg-config, see https://people.freedesktop.org/~dbn/pkg-config-guide.html

Would it be possible to provide a libpugixml.pc file?

**Comment by zeux** [comment]
pugixml can be built with pkg-config support; there's a BUILD_PKGCONFIG option you have to enable for that to work during a CMake build. It generates libpugixml.pc as part of the build process.

I'm not sure what exactly the linked issue is about though - it's not clear how meson discovers pugixml and also whether your installation of pugixml is pkgconfig-compatible (maybe some Linux distros use it and some don't? I don't have much visibility into this because packaging is different for different distributions and is handled by different package maintainers).

**Comment by legoktm** [comment]
Aha, thanks for that information, I wasn't aware of that. I'm using the Debian packaged version, which doesn't set that flag. I'll file a bug with the Debian maintainer. Building it manually works fine. Sorry about the false bug report.

**Comment by zeux** [comment]
FWIW pkgconfig support is new as of 1.8. And it should have been mentioned in the release notes but it wasn't :(

**Comment by orblivion** [comment]
Hello,

I'm following along on a trail blazed by @legoktm starting from another project (Kiwix). I'm unfamiliar with some of these build tools so I'm not piecing together what more experienced people understand implicitly. Could you clarify exactly how you install this library? I got as far as `make` but it doesn't put the resulting built files anywhere. There's no `make install`. I'm not sure where to put this `BUILD_PKGCONFIG` option.

Could you perhaps put some basic build instruction examples in your README? Or lay them out here and I could make a PR with it.

Thanks a lot!

**Comment by legoktm** [comment]
You need to use cmake, something like:
```
cmake -DBUILD_PKGCONFIG=1 -DBUILD_SHARED_LIBS=1
sudo make install
```

**Comment by samkellerhals** [comment]
@legoktm thank you very much for the heads up. 

I am using Raspbian stretch v.9.9 and have encountered the same issue during the meson build. Pugixml was nowhere to be found, so manually compiled using cmake and the `-DBUILD_PKGCONFIG=1 -DBUILD_SHARED_LIBS=1` flags which then resulted in pugixml being found during the meson build.

Thanks again!
