### ISSUE TITLE
Add vcpkg package

### ISSUE THREAD

**Issue by zeux** [zeux/pugixml#129]
It would be nice to have pugixml available as a vcpkg package.

I'm not sure if it requires any changes to pugixml repository or just a pull request to vcpkg ports with an appropriately setup CMake file.

**Comment by SinghRajenM** [comment]
@zeux ,
I'm not sure what you want to achieve with vcpkg. 
What I understood is, a package (setup file either exe or msi) which should extract pugiXml code somewhere (most probably in C:\ProgramFiles\PugiXml\........) and this path should be added to env variable. Later a developer can include this path to his any/all project(s) to make use of pugiXml with single copy instead of multiple copies in each project.
Is my understanding is correct? If so, I can give a try to create an exe setup. Or let me know what exactly needed? Thank you!

**Comment by zeux** [comment]
I don't know too much about vcpkg but my understanding is that this needs a metadata file that is committed to vcpkg project that tells it that pugixml sources are available from a certain GitHub URL or download link, so that if you are using vcpkg you can just reference pugixml from your configuration file.

I don't think it's about installing pugixml to Program Files - we may be talking about different package managers? This issue refers to https://github.com/Microsoft/vcpkg

**Comment by zeux** [comment]
This is apparently done :) as of https://github.com/Microsoft/vcpkg/commit/1b0fd3880fd3795b70235029c0c218cefff158db

Thanks, @ab-acx!
