### ISSUE TITLE
Any plans to add a SAX parser ?

### ISSUE THREAD

**Issue by silviucpp** [zeux/pugixml#135]
Or there is any way that the library can be used for parsing in streaming apps?

**Comment by zeux** [comment]
Unfortunately, pugixml is not made with streaming use case in mind. I think there are some pugixml users that do manual framing with string searches and parse the resulting buffers into fresh documents (say, expecting a stream of <message> nodes, you could find </message> with strstr and some manual buffer stitching). I don't necessarily recommend this approach - it's pragmatic but not robust to arbitrary changes in the input format :(

I've thought about adding a SAX mode, but my current understanding is that it's close to a complete rewrite - while some parsing techniques that are used can be adapted, a streaming parser that can have a guaranteed minimum working set (given some sensible requirements wrt document structure, like having a limit on the tag name length etc.) will have to do certain things like chunking PCDATA contents which seems like it renders all pugixml parsing code invalid.

I'll keep this issue open for now to see if others have comments and/or to gauge interest but the strengths of pugixml as I see them right now pretty much make SAX parser a separate effort which is not planned.

**Comment by silviucpp** [comment]
@zeux thanks for your reply. It's clear that a SAX mode will make a difference. right now I don't see to many libraries with good performances with SAX. I think the only option you have is expat which I don't think it's maintain any longer.

**Comment by halx99** [comment]
I have implemented a simple SAX parser for pugixml & rapidxml at here:
https://github.com/halx99/xmldrv3

**Comment by zeux** [comment]
This SAX parser is nice but unfortunately since it reuses the same parsing core/approach it requires the entire document buffer to be present up front, and to be mutable. What I had in mind when writing my original comment to this issue is a very different structure that would make it possible to e.g. parse a multi-gigabyte XML file in a small (several kilobytes) buffer, unless the XML in question has large text nodes - although even then it might make sense to segment these to guarantee the limited memory footprint.

**Comment by silviucpp** [comment]
Hello @zeux  I followed your advice and implemented in top of pugixml a small class with a minimum overhead that breaks the stream into independent stanzas: https://github.com/silviucpp/erlxml/blob/master/c_src/xmlstreamparser.cc . Once a complete stanza is found will be sent to pugixml. This seems to work pretty nice with our ejabberd servers and also parsing performance was improved a lot from 112.71 MB/sec with one of the most mature erlang parser based on expat to 558.53 MB/sec with this one based on pugixml. Of courser there are some limitations we don't care right now about like : 

1. not supporting cdata
2. not supporting comments with special xml charachters inside
3. not supporting doctype

Thanks for your advice,
Silviu

**Comment by zeux** [comment]
Since I currently see SAX parsing effort as a completely separate codebase without much opportunity for code sharing, I'll close this issue with `wontfix`. Please feel free to continue the discussion or share more links to code that can be used to assist pugixml in parsing data in a streamable fashion.
