### ISSUE TITLE
Private copy constructor and assignment operator

### ISSUE THREAD

**Issue by dpservis** [zeux/pugixml#141]
Hello

couldn't these be allowed? Do be honest I subclass from xml_document and make operator= and copy ctor public and it works fine but I have different semantics: the underlying assumption is that the document is unique which for me is a good premise for making sure that the whole thing is used wisely. When I use operator= it means that I need a copy of the document.

Thanks!

Dimitris

**Comment by zeux** [comment]
For explicitly copying a document from another document you can use `xml_document::reset`.

Documents are non-copyable because copying introduces both a performance issue and a correctness issue - accidentally copying a document means that all node objects you've retrieved from the document become invalid if the old document gets destroyed. This sometimes leads to issues in seemingly reasonable code.

The design basically is similar to your semantics - the underlying assumption is that document is unique, and when you need to copy a document it's very explicit - `doc.reset(doc2)`.
