### ISSUE TITLE
API/ABI changes review for pugixml

### ISSUE THREAD

**Issue by lvc** [zeux/pugixml#144]
The review of API/ABI changes for pugixml since 0.5 version: https://abi-laboratory.pro/tracker/timeline/pugixml/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![pugixml-1](https://cloud.githubusercontent.com/assets/1517837/25081351/df89c682-235a-11e7-930c-3228262657f8.png)
![pugixml-2](https://cloud.githubusercontent.com/assets/1517837/25081359/ed216cb4-235a-11e7-8b13-06c22c759bd9.png)

## Environment
* Linux x86_64
* GCC 4.9
* pugixml 0.5 and higher

**Comment by zeux** [comment]
Thanks, this is helpful. I believe the change in 1.7 is not ABI breaking because it changes the private symbol that's only referenced in the implementation; maybe abi-tracker can be extended to treat this case separately (assuming the private functions do not leak to calling code through public inline functions and are not virtual, it should be safe to add/remove/change them).

FWIW I used to use http://upstream.rosalinux.ru/versions/pugixml.html for ABI tracking before, good to know this tool lives on.

**Comment by lvc** [comment]
Should we exclude all xpath_* classes (declared in pugixml.hpp) or just one constructor from the analysis?

**Comment by zeux** [comment]
It's just the private constructor; public symbols of xpath_* classes still affect ABI compatibility.

A slightly broader statement for pugixml that I *think* is correct is that any private member function is only referenced from the .cpp file so can change at will without breaking ABI.

Now that I think about it, I might be able to adjust the symbol visibility setting so that these symbols don't even appear in the .so which would make sure this contract is preserved. This does mean that it becomes easier to break the dynamic linking build on Linux without noticing it - pugixml test suite currently doesn't verify that pugixml works when linked dynamically...

**Comment by lvc** [comment]
The removed c-tor is protected, not private (line 1043 in pugixml.hpp 1.6). Is it OK to remove it from the analysis?

Private symbols are not reported by the tool (if they don't affect public parts of the ABI interface).

**Comment by zeux** [comment]
Oh I see. That's kinda interesting.

The constructor is protected and it is used by xpath_variable implementations that are inside pugixml.cpp. However of course technically a user of the library can inherit from xpath_variable. There's no point doing that - I doubt any users do that - but if they do, this would be an ABI breaking change.

But yeah, this specific constructor is not supposed to be a part of public ABI and can be ignored.

**Comment by lvc** [comment]
Removed from the analysis:

    _ZN4pugi14xpath_variableC1Ev
    _ZN4pugi14xpath_variableC2Ev
    _ZN4pugi14xpath_variableC1ENS_16xpath_value_typeE
    _ZN4pugi14xpath_variableC2ENS_16xpath_value_typeE

Please let me know if it is necessary to ignore more symbols.

Thank you.
