### ISSUE TITLE
UTF-8 characters problems

### ISSUE THREAD

**Issue by silviucpp** [zeux/pugixml#162]
Hello,

Recently we discovered some xml that can be parsed with pugixml but not with any other XML parser (online parsers and also expat). 

We opened a ticket to expat and their answer was : 0xEF 0xBF 0xBF is U+FFFF, which is guaranteed never to be a Unicode character. By definition, any text containing it is not correctly encoded.

Files for testing are located: https://github.com/libexpat/libexpat/issues/136

Question is : is this a bug in pugixml which is not considering that chars invalid ?

Silviu

**Comment by zeux** [comment]
This is by design as documented at the end of https://pugixml.org/docs/manual.html#loading.encoding (although it should probably be mentioned in https://pugixml.org/docs/manual.html#loading.w3c as well - I'll add a note there). pugixml does not perform Unicode validation to maintain high parsing performance (which also helps for parsing documents that are *not* UTF-8 and instead are using another ASCII-compatible single or multi byte encoding). So it's expected that pugixml can parse this sequence while other parsers can't.

**Comment by silviucpp** [comment]
ok thanks, feel free to close this issue
