### ISSUE TITLE
Change the type of the existing node

### ISSUE THREAD

**Issue by ilya1725** [zeux/pugixml#164]
It would be nice to be able to change the type of an existing node. There is a method to add a new node with type designation - `xml_node append_child(xml_node_type type = node_element);`.  But no method I could find to change existing one. In particular I would like to be able to make a node a comment node.

**Comment by zeux** [comment]
What's the original node type?

**Comment by ilya1725** [comment]
It's the element/tag node (`node_element`)

**Comment by zeux** [comment]
This type of conversion requires changing the node contents pretty significantly, with some user judgment as to how it should be formatted - `node_comment` doesn't have any children and instead stores the text of the comment in `value()` (this is because comments don't necessarily contain valid XML content).

For converting an element into a comment, you'd want to use something along these lines:

	std::ostringstream oss;
	node.print(oss, "", pugi::format_raw);

	pugi::xml_node comment = node.parent().insert_child_before(pugi::node_comment, node);
	comment.set_value(oss.str().c_str());

	node.parent().remove_child(node);

Of course, depending on your formatting needs, you might want to adjust `node.print` arguments and/or add extra before/after whitespace to the string.
