### ISSUE TITLE
Double values are printed with insufficient precision

### ISSUE THREAD

**Issue by zeux** [zeux/pugixml#18]
This issue was filed on Google Code: https://code.google.com/p/pugixml/issues/detail?id=230

Ideally I would like to have perfect round-tripping of floats/doubles when using as_float/as_double. This would mean that setting double values results in much longer strings in general though since standard printf formats don't seem to support shortest-sufficiently-precise output...

At the very minimum this means extra overloads for set_value(float) to keep floats at %.9g (or whatever the correct format is).

**Comment by zeux** [comment]
Fixed in 550ab4b6356ba203acb6aaebcd3d41acb9e1fa4a

**Comment by mikejiang** [comment]
It would be helpful to allow the precision digits to be customized (say through `set_value` API). here is the use case: we are porting an xml file generator written in `R` into `c++` using pugixml, the default precision of casting `double` to `string` is 15, which causes the testing failed due to the mismatch between two outputs

**Comment by zeux** [comment]
Yup this makes a lot of sense. Can you open a new issue for this?
