### ISSUE TITLE
Use C++ headers

### ISSUE THREAD

**Issue by gcey** [zeux/pugixml#181]
In pugixml.h please replace
#include &lt;stddef.h&gt;
by
#include &lt;cstddef&gt;

In pugixml.cpp please replace all
#include &lt;XXXXX.h&gt;
by
#include &lt;cXXXXX&gt;

In this way you comply to the C++ standard.

I had the problem, that LLONG_MIN, LLONG_MAX and ULLONG_MAX were undefined with
#include &lt;limits.h&gt;
but they are now defined after I changed this line to
#include &lt;climits&gt;

**Comment by zeux** [comment]
My best guess is that you're experiencing something similar to https://github.com/zeux/pugixml/issues/66. If you want to help resolve this, we can try to figure this out and I can apply a workaround in pugixml source code - specifically, you'll need to figure out which limits.h pugixml is including:

    gcc pugixml.cpp -E | grep limits.h

And upload the resulting file here. Please also specify the compiler, compiler version and OS you have this issue on.

I'm extremely reluctant to actually change C-style headers to C++ wrappers. C++ standard does not force you to use C++ headers, and in many environments pugixml builds on there are various issues with C++ headers (for example, some compilers didn't define some symbols in global namespace when including C++ wrappers and some other compilers didn't define the same symbols in std:: namespace, which required complex workarounds). The only issue with C headers I've had since 2010 or so when this was changed is the limits.h issue that is relatively recent.

**Comment by gcey** [comment]
The problem occurs with this compiler: powerpc-rtems4.12-gcc.exe (GCC) 6.3.0

/opt/rtems/bin/powerpc-rtems4.12-gcc.exe -E -MT obj/pugixml.o -MMD -MP -MF .d/pugixml.Td -mcpu=e6500 -x c++ -std=gnu++14 -g -m32 -maltivec -mvrsave -ftls-model=local-exec -msdata=sysv -fno-common -fno-openmp -mbig -mmultiple -mno-string -misel -mstrict-align -fverbose-asm -fsanitize=unreachable -fno-exceptions -fno-rtti -ftemplate-backtrace-limit=20 -G 8 -O3 -Wall -Werror -I/opt/rtems/lib/gcc/powerpc-rtems4.12/6.3.0/include/c++ -I/opt/rtems/lib/gcc/powerpc-rtems4.12/6.3.0/include/c++/powerpc-rtems4.12 -I/opt/rtems/lib/gcc/powerpc-rtems4.12/6.3.0/include/c++/backward -I/opt/rtems/lib/gcc/powerpc-rtems4.12/6.3.0/include -I/opt/rtems/lib/gcc/powerpc-rtems4.12/6.3.0/include-fixed -I/opt/rtems/powerpc-rtems4.12/include -I/opt/rtems/powerpc-rtems4.12/qoriq_t4240rdb/lib/include -I. -Iinc -Iobj -DRTEMS_GNU -D__ppc_generic -DSEU_gppc6rtems412  -DDEVENV -DTOOL_FAMILY=gnu -DTOOL=gnu -Iobj -DSEP5_4240 -DAPPLIKATION -g -DELM_FILE_ID_=pugixml_cpp src/pugixml.cpp | grep limits.h
produces the following output (I replaced my root path by "..."):
1 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\limits.h" 1 3 4
34 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\limits.h" 3 4
1 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\syslimits.h" 1 3 4
1 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\limits.h" 1 3 4
168 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\limits.h" 3 4
1 "...\\opt\\rtems\\powerpc-rtems4.12\\include\\limits.h" 1 3 4
17 "...\\opt\\rtems\\powerpc-rtems4.12\\include\\limits.h" 3 4
1 "...\\opt\\rtems\\powerpc-rtems4.12\\include\\sys\\syslimits.h" 1 3 4
18 "...\\opt\\rtems\\powerpc-rtems4.12\\include\\limits.h" 2 3 4
169 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\limits.h" 2 3 4
8 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\syslimits.h" 2 3 4
35 "...\\opt\\rtems\\lib\\gcc\\powerpc-rtems4.12\\6.3.0\\include-fixed\\limits.h" 2 3 4

The file "...\opt\rtems\lib\gcc\powerpc-rtems4.12\6.3.0\include-fixed\limits.h" contains this:
...
#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Minimum and maximum values a `signed long long int' can hold.  */
# undef LLONG_MIN
# define LLONG_MIN (-LLONG_MAX - 1LL)
# undef LLONG_MAX
# define LLONG_MAX __LONG_LONG_MAX__

/* Maximum value an `unsigned long long int' can hold.  (Minimum is 0).  */
# undef ULLONG_MAX
# define ULLONG_MAX (LLONG_MAX * 2ULL + 1ULL)
#endif
...

[limits_h.zip](https://github.com/zeux/pugixml/files/1748122/limits_h.zip)

**Comment by zeux** [comment]
Ok - thanks - it's indeed very similar to #66 but the workaround in #66 was specific to MinGW. I'll apply a better workaround.

**Comment by gcey** [comment]
Is there a plan, when this change will be officially released?

**Comment by zeux** [comment]
This change would go into 1.9; as to when it's going to be released I'm not sure exactly - I have a few things I want to do for that release still so my best guess is it'll happen in a month or two.
