### ISSUE TITLE
Proposal: const_xml_node etc.

### ISSUE THREAD

**Issue by brandl-muc** [zeux/pugixml#188]
I'm using a lot of `const` in my code. In consequence I find the const/non-const behavior of `xml_node`s peculiar.

`xml_nodes` conceptually are similar to pointers (and iterators). A pointer supports two different kinds of constness, the pointer can be const (as in `int * const ptr`) or the pointee can be const (as in `int const * ptr`). The same idea is true for iterators which might be const (`iterator const iter`) or the iterator might be a `const_iterator`.
Because a `xml_node const` actually is similar to a `int const * const ptr` (one  cannot change the pointee (node data) nor the pointer (node instance)) it has weird behavior in my opinion.

Therefore I propose to introduce a `const_xml_node` which does not allow to change the data but which can be changed to point to a new node. Of course this involves adding a lot of overloads (similar to `std::vector::begin() const` and `std::vector::begin()`), also for other pointer-like structures which makes it more like a 2.0 feature, but I believe that it would increase usability.

Depending on the timing I would also offer to assist.

**Comment by brandl-muc** [comment]
I forgot, not only does the current state feel peculiar, it also breaks const-correctness. I would need to pass my node to a function as `xml_node const &` to prohibit changeing my `xml_document`. But that is overload as `sizeof(xml_node) == sizeof(void*)`. Passing the node by value leads to a copy which drops constness.

**Comment by zeux** [comment]
This has come up before; I can't find the correspondence :( but it has been suggested before by one or two people and I have thought about this several times.

My general feeling on this is that it's not worth the cost. I think that when I looked at this last time, it looked like a significant increase of the API surface for marginal wins. I don't agree with the "increase usability" moniker - I have never been asked about this with a pretext of not understanding how the API works or why the code doesn't compile. I agree that it would make certain uses of the API safer of course - particularly if you are writing a multithreaded application, it might be nice to get a `xml_const_node` object from the document and then the type system would ensure you'd never get back to `xml_node`, making the code provably safe in this regard.

OTOH it also seemed to me like this could be done as an external layer/helper class - say, `xml_node` is kept as is (which still means that you can't call `append_child` on a `const xml_node` object which might seem slightly weird but I'm not sure it actually gets in the way), and `xml_const_node` just wraps `xml_node` and provides read-only methods and an implicit ctor from `xml_node`.

So, obviously feel free to experiment with this idea etc but I'm not sold on it as mentioned above. If this ever does happen it would likely be an ABI-breaking change since mutation methods on `xml_node` would need to become const, so that won't really happen until 2.0 anyway.

**Comment by zeux** [comment]
Closing as wontfix for now since this extension seems to add a large amount of API surface and the gains are not clear. Any further thoughts on the matter are welcome in comments.
