### ISSUE TITLE
xml_attribute add set_format_value

### ISSUE THREAD

**Issue by irov** [zeux/pugixml#199]
bool set_format_value(const char_t* fmt, ...);

**Comment by tuananh** [comment]
is there more descriptive version of what this would do?

**Comment by zeux** [comment]
FWIW I'm having second thoughts about this - I initially thought that it's a good idea, but it's common to have helper functions similar to this outside of any libraries in C++ codebases (e.g. format(...) that returns std::string); exposing this in pugixml's interface will forever tie pugixml implementation to sprintf, and the implementation here is somewhat involved - the maximum size isn't known apriori so there's a fair bit of complexity with establishing it precisely on *all* compilers and platforms pugixml supports (which is a lot).

Since there hasn't been any feedback on this issue I assume the need isn't very significant and I'll close it.
