### ISSUE TITLE
Need fixed-width integer conversions

### ISSUE THREAD

**Issue by hofmand** [zeux/pugixml#202]
I need to read an integer attribute that can be in the range of 1..999999. I can't use `pugi::xml_attribute::as_uint()` portably because [C/C++ only guarantees that `unsigned int` must hold a number in the range of 0..65535](https://stackoverflow.com/a/1819236).

`cstdint`/`stdint.h` provide a number of fixed-width integer types. It would be good if pugixml could support these somehow.

For now I will use `as_ullong()` and cast to `uint_fast32_t`.

**Comment by zeux** [comment]
I would advise using as_uint() for this. stdint.h isn't universally available - see pugixml.cpp for internal fixed-width types pugixml uses - and I do not want to clutter interface for platforms where int isn't 32-bit because they are very non-mainstream. If this is a legitimate concern on your platform - that is, if you have a specific target that uses 16-bit integers that you want to target - you can always use smth like `strtoul` if `long long` is not available or too long on the platform of choice.

**Comment by zeux** [comment]
Closing as wontfix; if there's any further thoughts on this issue feel free to comment here - if there's enough demand for this this can be reconsidered.
