### ISSUE TITLE
Offer a better API reference

### ISSUE THREAD

**Issue by ruimaciel** [zeux/pugixml#226]
It would be awesome if pugixml made available an API reference that was easy to navigate and read. 
For reference, here's Qt's documentation of its QDomDocument class: http://doc.qt.io/qt-5/qdomdocument.html

Although pugixml's manual includes some info, it's hard to navigate and to avoid all the noise created by unrelated info.  If it was possible to offer the same type of content but in a more polished and uncluttered format then the user experience of getting started with pugixml would be significantly improved.

**Comment by zeux** [comment]
API reference is a bad way to start using pugixml - quick start guide is more appropriate. FWIW long time ago pugixml used Doxygen-like documentation similarly to what Qt has. I had complaints from people who found it hard to read the header that was cluttered with boilerplate, and from people who found it hard to understand the general rules from an API reference. Subsequently, to address both issues, documentation was rewritten into the current form, with API reference linking to descriptions of function behavior and related functions. Long comments in source were replaced with a single-line brief comment that describes each member - which is often enough to understand the behavior.

I'm definitely not going to rework the documentation again, sorry. If any links in the reference are inaccurate or could be better placed, or if API feels like it deserves a separate section and doesn't have one right now and links into a generic text feel free to file concrete issues. Otherwise as far as I'm concerned, the current documentation is a better balance overall.
