### ISSUE TITLE
About Python Binding 

### ISSUE THREAD

**Issue by blackball** [zeux/pugixml#246]
Hi, 

Is there any plan on providing a Python binding for pugixml ? I couldn't find an update-to-date python binding online. 

Thanks!

**Comment by zeux** [comment]
Is https://github.com/semigodking/pugi out of date? It looks like it's a year old which should mean it's still API compatible - the version 1.9 that released since then has internal compatibility and performance improvements but doesn't have interface changes.

In general pugixml is a C++ library, and the expectation is that all bindings for other languages are developed separately in separate libraries/repositories.

**Comment by blackball** [comment]
I though that binding was out-dated. Will verify it. Thanks!
