### ISSUE TITLE
Form feed character is encoded as &#12; which is invalid xml 1.0

### ISSUE THREAD

**Issue by Yanpas** [zeux/pugixml#262]
`\f` character after decoding xml tree to string becomes `&#12;`. Well, any character within range [1; 31] except some valid ones (`\t \n \r`) is encoded this way.

**Comment by Yanpas** [comment]
IMO this option must be on by default.

Validator which I do use: https://www.xmlvalidation.com/

W3C https://www.w3.org/TR/2006/REC-xml11-20060816/#charsets

**Comment by zeux** [comment]
I agree the flag would be a good addition, but I think defaulting to false is good for now. It maintains backwards compatibility and also silently losing data isn’t great since pugixml itself can easily parse the results. This falls into the gray area of “user supplied data that can’t be encoded into XML”.

**Comment by Yanpas** [comment]
I think in addition to default flags, some flags set called `std` may be introduced. It groups all flags that guarantee to produce valid XML.
