### ISSUE TITLE
Why is the file pugixml/contrib/foreach.hpp under Public domain and not under MIT ?

### ISSUE THREAD

**Issue by SOesterreicher** [zeux/pugixml#264]
Hello,
why is the file  pugixml/contrib/foreach.hpp under Public Domain licensed and not under MIT like all other files of pugixml? 
Public Domain is not easy to use in Gemany due to specific Copyright laws.

Is there a possibility to get the pugixml/contrib/foreach.hpp file under the MIT license?

Thanks in advance.
Siegfried Oesterreicher

**Comment by zeux** [comment]
Huh - I'm not quite sure, it somehow started as public domain ~9 years ago. Are you using foreach.hpp, or is the mere presence of the file problematic? fwiw I was thinking of removing it for unrelated reasons - it is not necessary anymore, since instead of `children(doc)` you should be able to use `doc.children()`.

**Comment by hobbes1069** [comment]
It's typically not a huge problem, but technically "Public Domain" isn't a license, which gives some distros heartburn.

**Comment by SOesterreicher** [comment]
Thank you very much.
