### ISSUE TITLE
Improving performance on loading any xml data

### ISSUE THREAD

**Issue by chaipu88** [zeux/pugixml#284]
Hi,

What i found is after using pugi::parse_full flag instead of pugi::parse_default while loading, time taken to load large xml file was little less. Please verify if it is correct ?

And also is there any way to increase the performance on reading ?

Thanks

**Comment by zeux** [comment]
> What i found is after using pugi::parse_full flag instead of pugi::parse_default while loading, time taken to load large xml file was little less. Please verify if it is correct ?

Generally speaking `parse_full` performance should be the same as that of `parse_default`. Can you share your performance numbers?

> And also is there any way to increase the performance on reading ?

Can you elaborate?

**Comment by chaipu88** [comment]
> Generally speaking parse_full performance should be the same as that of parse_default. Can you share your performance numbers?

Actually we just ran a test application and loaded 350MB xml file multiple times with parser_full and parse_default options. And we found that with parser_default, it was taking ~0.810897 secs (0.80 to .82 secs) to load and parser_full was taking taking ~0.80253 seconds  (from 0.79 secs to 0.81 secs).

> Can you elaborate?

yes, actually i wanted to know, whether there are any other options / ways like parser_full / parser_default which has some impact in performance while loading. As for us, even a very little different can bring up a huge impact for our application.

-Thanks

**Comment by zeux** [comment]
It's somewhat surprising to see the delta in this direction - I'm assuming you're measuring just the document load time? Still, the delta is small enough that maybe it's either noise or some unexpected microarchitectural effect that happens to affect your document. The only significant difference is that parse_full preserves comments as node_comment nodes, but if you don't have many comments in the file I don't see why the parse time would be different at all.

In terms of optimizing the parsing times - please note that I'm only talking about the parsing into xml_document, but you should make sure that the processing time of the document is optimal as well - there's a few things you can make sure of / try:

1. parse_default consists of the following flags:
```
const unsigned int parse_default = parse_cdata | parse_escapes | parse_wconv_attribute | parse_eol;
```

`parse_escapes` performs escape processing by replacing `&quot;` with `"` etc.
`parse_wconv_attribute` performs attribute value processing by substituting newlines with spaces inside attribute values
`parse_eol` performs newline normalization by replacing Windows newlines (`\r\n`) with Unix newlines (`\n`) inside PCDATA (text) blocks.

You can consider removing parse_wconv_attribute & parse_eol and parsing with just parse_cdata | parse_escapes, since this is usually harmless for most documents (aka the results are the same or similar). parse_escapes is usually necessary to get a correct parse. I don't think this will help too much but worth trying.

2. If you are using loading from std::istream, you should consider *not* doing that and letting pugixml load the file by itself (via `load_file`) or loading using some other mechanism (not istream) into memory and loading the document from memory. istreams aren't efficient and they will eat up into your loading time.

3. If you are loading from a memory buffer, you should consider using `load_buffer_inplace` if you use `load_buffer` - if the document doesn't go through encoding conversion, this is generally notably faster than `load_buffer`.
