### ISSUE TITLE
node.child_value('Host') vs node.child('Host').value()

### ISSUE THREAD

**Issue by DeadBoolean** [zeux/pugixml#290]
Hello,

i think i have a misunderstaning how the value/node access works. 

Why node.child_value('Host') is working (returns the correct value) while
node.child('Host').value() returns an empty string? 
node.child('Host') should return the node and i schould be able to acces the value, oder isn't it? 
Hope you can explain...
regards

**Comment by zeux** [comment]
This is because plain character data lives in its own node; a motivating example is `<Host>one<child/>two</Host>` - there are *two* PCDATA nodes in this example, and Host node by itself doesn't have a value.

https://pugixml.org/docs/manual.html#dom.tree
https://pugixml.org/docs/manual.html#access.text
