### ISSUE TITLE
Modernize CMake files

### ISSUE THREAD

**Issue by slurps-mad-rips** [zeux/pugixml#301]
Hi! I'm a bit of a CMake expert and I've been going around to various projects that are well known in the C++ community and helping fix their `CMakeLists.txt` files so that they are neat, clean, *actually readable* (ish, because, hey its CMake) and meet modern requirements for CMake. I'm willing to do the heavy lifting here (and by that I mean all of it), but I was wondering if you have any desired requirements? Currently modern distros support much more recent versions, but even then using CMake 3.4 can be considered a "conservative" approach.

I'll be submitting a PR in the near future, but figured I'd open an issue for discussion so you don't get blindsided with a diff for your build files :)

**Comment by zeux** [comment]
No specific requirements other than a desire to keep the existing configurations in tact - the CMake config is used a lot by various Linux distributions for packaging, by various projects when including pugixml as a dependency, and for direct builds (which is why there are some potentially unconventional config options, e.g. for building both static & shared libraries in one go).

So I'd prefer to see local cleanup as opposed to "hey here's a completely new CMake file" because then it would be hard for me to figure out if it works for all the different use cases in the same way since there's no real way to test *all* of these.

In terms of CMake versions, while I don't have a specific version cutoff, Ubuntu 16.04 LTS which is still supported comes with CMake 3.5, so it would be nice to either keep the CMake version under this, or have any new features used conditionally. Then it would be possible to remove the support for older CMake versions in a few years via simple refactoring.

**Comment by slurps-mad-rips** [comment]
Perfect! I am working on a refactor on my branch but that was more to get a better idea of what would need to be done regarding changes. Currently my plan is to sort of split the approach into two the following use cases:

1) Existing workflow of options and settings.
2) `add_subdirectory`

In the former case, all options will be enabled and available with the current defaults as long as pugixml is being built by itself. The latter will lock out some things like, running the unit tests, adding an `ALIAS` library so one can do `pugixml::pugixml` in `target_link_libraries`, etc.

I do want to maybe take a crack at cleaning up the `__declspec(dllexport)` logic a bit. CMake does have a `GenerateExportHeader` module which technically does everything you're currently doing via `target_compile_definitions`. This would be a 'breaking' change in that an additional header might get installed along with everything else, but I reckon that shouldn't be too much of an issue if someone packages the new version along and installs it? If you think this is rocking the boat a bit too much, then no worries. I can always try to tackle that another day :)
