### ISSUE TITLE
Potential null pointer dereference in `node_copy_tree()` function

### ISSUE THREAD

**Issue by valeriyvan** [zeux/pugixml#314]
Static analyser of Xcode (version 11.2.1) reports potential null pointer dereference in `node_copy_tree()` function:

<img width="1169" alt="Screenshot 2019-12-03 at 11 00 13" src="https://user-images.githubusercontent.com/1630974/70040833-70e03c00-15bc-11ea-8f4d-e518c3b6a556.png">

**Comment by zeux** [comment]
Root cause here is that `sit` & `dit` are tied together through a loop invariant (roughly, tree-depth-distance from `sn` to `sit` is one larger than `dn` to `dit`) which makes it so `dit` can never be null but the analyzer doesn't understand this. Adding null pointer checks to both inner and outer loop "solves" this but I'd like to find a different solution.
