### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by haseeb-heaven** [zeux/pugixml#325]
There is no exception handling at all and no error checking like if file not found we have to check it manually,

```
result = doc.load_file("demo.xml");
if(!result)
{
    std::cout << result.description() << std::endl;
}

```
Like in **RapidXML** there is exception handling in whole library ,please add **exception handling** and **automatic error detection.**

**Comment by zeux** [comment]
pugixml uses exceptions in one place - in XPath engine.

It’s one of the few things I regret. It will likely change if I figure out a way to smoothly transition existing API.

Exceptions are not used by many users in the C++ community due to associated cost and implicit control flow that obscures error sources. Relying on them thus fragments the interface.

Highly recommended talk: https://m.youtube.com/watch?v=os7cqJ5qlzo
