### ISSUE TITLE
pugixml accepts input which is not well-formed XML

### ISSUE THREAD

**Issue by Bu11etmagnet** [zeux/pugixml#337]
After creating a `pugi::xml_document` and calling `load_file` with a file containing
```
<?xml version="1.0"?>
<m>
	<v>42</v>
</m>
<d>
        <i>eek</i>
</d>
```
a successful `xml_parse_result` is returned. Both `doc.child("m").child("v")` and `doc.child("d").child("i")` return a valid `pugi::xml_node`.

The input is not well-formed, because

> There is a single "root" element that contains all the other elements.

<https://www.w3.org/TR/xml/#dt-root>

> Validating and non-validating processors alike MUST report violations of this specification's well-formedness constraints in the content of the document entity and any other parsed entities that they read.

<https://www.w3.org/TR/xml/#proc-types>

**Comment by zeux** [comment]
I'm assuming `</m>` is actually `</ma>`?

Otherwise this is somewhat intentional - pugixml didn't used to have a fragment option, and multiple roots are common enough in practice that this was allowed unconditionally.

It's possible to disallow this unless `parse_fragment` is specified - this would be a breaking change though...

**Comment by Bu11etmagnet** [comment]
Documents with multiple roots are not well-formed XML. Accepting them makes pugixml a non-conforming parser.

**Comment by zeux** [comment]
Sure, this is documented here: https://pugixml.org/docs/manual.html#loading.w3c, although it looks like the specific issue here is not covered. It’s not a performance concern to reject documents with multiple roots, but it is a compatibility concern.

**Comment by Bu11etmagnet** [comment]
> You can get very substantial performance improvements
> by not doing the right thing. - Scott Meyers, An Effective C++11/14 Sampler
<https://www.youtube.com/watch?v=BezbcQIuCsY&feature=youtu.be&t=2190>

**Comment by zeux** [comment]
Sorry, I'm not sure how to answer that, but I would appreciate keeping the discussion constructive. As I mentioned this is not a performance concern, but it's a compatibility concern as upgrading to a version that starts prohibiting this would break existing users that don't care to learn what differentiates a conformant XML document from a non-conformant one. This is not saying that this should not be fixed, but this is saying that it should perhaps not be fixed blindly.

**Comment by erengy** [comment]
I think mentioning this specific case at [section 4.7](https://pugixml.org/docs/manual.html#loading.w3c) of the manual would be a good start.

I'd also suggest making a slight change to [section 3.1](https://pugixml.org/docs/manual.html#dom.tree), as it might give the wrong idea that the document itself is the root element. I'd argue that most people who use pugixml or a similar library do not actually read the relevant specification. This is kind of what happened in my case: I've been using pugixml since 2010 and I didn't know about this issue until a couple of months ago. Adding something along the lines of the following sentence to section 3.1 could help:

> Note that a well-formed `node_document` is required to have exactly one child `node_element`.

Looking at section 4.7 again, it seems pugixml is somewhat lenient in terms of validation, so fixing this specific issue while ignoring other well-formedness checks doesn't seem reasonable to me. If there's any interest, you could consider adding a strict parsing option and perhaps making it the default behavior in a major release, though I'm not sure if it'd be worth the additional complexity.

**Comment by zeux** [comment]
Yeah, really this is an omission from a few years ago - when `parse_fragment` option was introduced (which was v1.4) it probably made sense to consider a breaking change but at this point it's not obviously correct.

Since this is something that's easy to check after the document is parsed, I'm going to treat this as a documentation issue for now; it's always possible to reconsider. I don't have a specific timeline for v2.0 but if that ever happens this could be a good candidate for a behavior change at that point.

**Comment by zeux** [comment]
I'm going to keep the "root" terminology as is in the manual for now. Unfortunately the terminology is different between the standard and the pugixml API/documentation, in pugixml terms root is the *root node* of the tree, which - for valid XML documents - will contain a single element node (called document_element), but can also contain other nodes such as comments or processing instructions or document declaration. pugixml terminology matches the general CS tree terminology though, and it's already reflected in the API (xml_node::root) so isn't really changeable.

I'm going to amend the "tree structure" documentation section slightly to note the role of a document element.
