### ISSUE TITLE
Multiple targets with the name libpugixml.a doesn't work with CMake+Ninja

### ISSUE THREAD

**Issue by jhasse** [zeux/pugixml#344]
```
$ cmake -Bbuild -H. -GNinja
-- The CXX compiler identification is GNU 10.0.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jhasse/git/pugixml/build
$ ninja -Cbuild
ninja: Entering directory `build'
ninja: error: build.ninja:388: multiple rules generate libpugixml.a [-w dupbuild=err]
```

This is with CMake 3.17.1 and Ninja 1.10.0 and happens since https://github.com/zeux/pugixml/commit/2c24e90c238e5142edb389c2a9735a9c1bae9039.

I think it isn't save to have to targets with the same name?

**Comment by zeux** [comment]
@LocutusOfBorg Any thoughts? I don't have the necessary context re: pkg-config. Unsure if that PR was fixing a regression from the CMake rework by @slurps-mad-rips or if the issue was long-standing/separate?

**Comment by slurps-mad-rips** [comment]
@zeux that PR is definitely what led to it, however the issue is a result of the fix not being the correct approach here. It makes every static library have the same output name. 

```
add_library(pugixml) # Auto selects static or shared based on BUILD_SHARED_LIBS
add_library(pugixml-shared SHARED)
add_library(pugixml-static STATIC)
```
This in particular means that if `BUILD_SHARED_LIBS` is set to `OFF`, `pugixml` and `pugixml-static` will be built as... well `libpugixml.a`. If `pkg-config` is involved, all the scripts need to do (prior to that commit) is set `BUILD_SHARED_LIBS` to `ON`. 

Alternatively, only set `OUTPUT_NAME` to be set when `BUILD_STATIC_AND_SHARED_LIBS` is set to `ON`.

Up to you which path is taken 🙂
