### ISSUE TITLE
[question] Can we expect pugijson?

### ISSUE THREAD

**Issue by ribtoks** [zeux/pugixml#351]
Hi

Thanks for this awesome library. It's a great piece of engineering!

Any plans to cover json as well?

**Comment by tuananh** [comment]
I find https://github.com/chadaustin/sajson pretty good. You may give it a try.

**Comment by ribtoks** [comment]
@tuananh thanks for the tip!

**Comment by zeux** [comment]
Thanks for asking, this is a question I get from time to time, so it's good to have a place to respond - the answer is "no".

There's a couple of reasons for this.

One, pugixml took a lot of effort to develop and takes some effort to maintain. Another library would take a lot of time as well, if it's built to the same quality standards.

Two, I personally don't find the idea of writing a JSON parser interesting - 10+ years ago pugixml was born out of a specific need (to parse hundreds of megabytes of XML files quickly) and as a result a lot of challenging problems had to be solved re: performance, clean interface, a robust XPath 1 engine, finding the balance between speed/usability/conformance, etc. - but it's not really fun to do it all over again.

Three, there's already a lot of JSON libraries out there, and one more will just be that, one more. There's plenty of libraries for JSON that span the entire gamut of "minimal token list" (jsmn) to lots of DOM-based libraries. I don't have a recommended JSON library because I don't love any of them, but there's so many that at least one must be good enough for any specific use case :) It doesn't even make sense to compete on the performance front because simdjson has every other library beat on that regard.
