### ISSUE TITLE
Parsing cdata that is using "/*<![CDATA[*/" and "/*]]>*/" as delimiters, instead of "<![CDATA[" and "]]>"

### ISSUE THREAD

**Issue by turgu1** [zeux/pugixml#432]
Greatings,

I'm facing an issue with CDATA that uses commented delimiters instead of the usual ones. Of course, the usual ones are very easy to parse...I have no control on the XML content as it is supplied by a remote app. Is there any way I can parse this using pugixml?

Thanks for that great tool!
Guy

**Comment by zeux** [comment]
This would require a very non-trivial modification to the parser, since not only do you need to modify CDATA parsing rules, you also need to modify PCDATA (text) parsing rules to recognize `/*<` as a terminator, which is multiple characters.

It's the first time I've heard of this delimiter sequence. If this is correct then the files encoded with it are certainly not XML. My only suggestion would be to parse the file as normal, hoping that unadorned CDATA doesn't show up elsewhere in the file, and then process the text on the application level - for contents like this:

```
<node>foo/*<![CDATA[*/bar/*]]>*/baz</node>
```

You are going to get three children of `node`: first with type `node_pcdata` and value `foo/*`, second with type `node_cdata` and value `*/bar/*`, third with type `node_pcdata` and value `*/baz`. You can then strip the redundant `/*` and `*/` at the application level.

This naturally doesn't work if somewhere in the file `<![CDATA` is meant to be encoded verbatim, not as a CDATA section, but that seems like the best possible alternative here other than encoding CDATA per actual XML rules in the producer.

**Comment by turgu1** [comment]
This commented method seems to be used often with <style> tags in EPub ebooks to allow them to be manageable in web browsers. Thanks for your reply. I’ve modified the stream to uncomment the <![CDATA[ and ]]>.
