### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [zeux/pugixml#439]
I think that it would be good to flush currently committed changes and make a new release :)

**Comment by zeux** [comment]
Usually the new releases are made when there's enough accumulated changes of importance; in this case I don't think the changes since last release justify making a new one just yet, plus a significant CMake change was committed just last month and it's too early to make a new release without that having been in the git repository for a while to make sure that any problems with it get a chance to get reported.

**Comment by kloczek** [comment]
Tested. All looks clean.
Thank you :)
