### ISSUE TITLE
compile error for xml_document declaration in class

### ISSUE THREAD

**Issue by luminize** [zeux/pugixml#471]
Hi,

I'm trying to use pugixml in a project where i'll be modifying an xml file (of course).
Declaring the xml_document in my program_handler class gives me a compile error. Complaining about attempting to reference a deleted function. Pointing to [this MSVC compiler error C2208](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2280?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2280);%26rd%3Dtrue&view=msvc-170)

I'm afraid my level of programming is not up to par but I hope you can point me in the correct direction on how to correctly declare and instantiate an xml_document.

```cpp
#pragma once

#include "pugixml.hpp"
#include <string>

class program_handler
{
public:
	
	program_handler(std::string iname);
	~program_handler();

	void set_filename(std::string fname);
	int load_xml_file();
	std::string get_name();

private:
	std::string name="", filename="";
	pugi::xml_document xml_file;

protected:

};
```

**Comment by brandl-muc** [comment]
Your code snippet is not complete, but the best guess is, that you are trying to copy a `program_handler` instance. To be able to copy that you would also need to copy `xml_document`. Since this class contains all the memory etc. you cannot copy it, only [move](https://stackoverflow.com/questions/3106110/what-is-move-semantics) it.

You need to avoid the copy. Without the code that is triggering the error one can only guess how to achieve this.
You can try to move the `program_handler` instead of copying it. That should work out of the box, the necessary ctor and assignment operator should be implicitly defined.

On a side note, if you define a custom destructor you will most likely need to also define custom copy and move ctors and assignment operators. (or delete them)
See [rule of zero or five](https://en.cppreference.com/w/cpp/language/rule_of_three)

**Comment by luminize** [comment]
hi @brandl-muc Thanks for your help
I add a few instances of this class `program_handler` to a vector somewhere else in my program.
```cpp
	for (auto& hname : {"source", "workbench", "output"})
	{
		program_handler_list.push_back(program_handler(hname));
	}
```
when I add a program_handler instance to my class as a variable instead of adding multiple to the vector I can use the xml_document. Guess the problem is in my own class. I will have a proper readup on constructors an destructors  :-(

in class header:
```cpp
private:
	std::vector<program_handler> program_handler_list = {};
	program_handler testprog;
```
and class constructor
```cpp
cMain::cMain() : frameMain(nullptr, wxID_ANY, "Windowtitle"), testprog("test")
```
I'll close this issue since it is not an issue with this library.

**Comment by brandl-muc** [comment]
Your problem is the push_back, that would need to copy the temporary into the vector memory. You could use emplace_back() to construct the `program_handler`s in-place.

(if `program_handler` is not nothrow move constructible then this will not suffice because the vector will need to copy the elements when allocating a bigger buffer, but I would expect that that will not be a problem)

**Comment by luminize** [comment]
@brandl-muc thank you for the replies, I've read the links you posted and after letting this ferment for the night I've understood and implemented a copy constructor and proper destructor for the `program_handler` class. Thanks, learned something important! For those whom it may help, I've solved it like this:

header
```cpp
class program_handler
{
public:
	
	program_handler(std::string iname);
	program_handler(program_handler&& rval) noexcept;
	~program_handler();

	void set_filename(std::string fname);
	int load_xml_file();
	std::string get_name();
	std::string get_xml_docname();
	
private:
	std::string name="", filename="";
	pugi::xml_document *xml_file = nullptr;

protected:

};
```

source file
```cpp
#include "program_handler.h"
#include "pugixml.hpp"

program_handler::program_handler(std::string iname)
{
	name = iname;
	xml_file = new pugi::xml_document();
}

// copy constructor
program_handler::program_handler(program_handler&& rval) noexcept
{
	name = rval.name;
	filename = rval.filename;
	xml_file = rval.xml_file;
	// make sure the "old" pointer can be deleted in the destructor
	rval.xml_file = nullptr;
}

// destructor
program_handler::~program_handler()
{
	// prevent memory leak
	delete xml_file;
}

```

**Comment by brandl-muc** [comment]
`xml_document` already has a move constructor (NOT copy constructor as you've written in your comment), so the following should work:

header
```
class program_handler
{
public:
	program_handler(std::string iname);
	// set_filename etc ...

private:
	std::string name="", filename="";
	pugi::xml_document xml_file;
};
```

source
```
#include "program_handler.h"
#include "pugixml.hpp"

program_handler::program_handler(std::string iname)
    : name(std::move(iname))
{}
```

Way less code and does what you want. If you really need to have `xml_file` on the heap then use [`unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr) instead of manually managing owning raw pointers. (your manual move ctor would be more efficient if it moved all member btw)
