### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [zeux/pugixml#475]
Hey there!

I belong to an open source security research community, and a member (@asteriska8) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by zeux** [comment]
My GitHub profile should have the email visible; I'll add this to SECURITY.md later.

**Comment by JamieSlome** [comment]
@zeux - great, much appreciated! ❤️ 

Just for reference, the report can be found directly here:

https://huntr.dev/bounties/0607e0cf-e4cd-4256-ae06-46c566ba3cfa/

**Comment by zeux** [comment]
This is not a vulnerability or a bug in pugixml; it was fixed in the library that depends on pugixml (not sure if I can call it out since the bug report is private) yesterday by fixing the code that computes the size to pass to the downstream format parsers; pugixml will load the buffer of a given size if it's told to.
