### ISSUE TITLE
Lack of abs(number) xpath function

### ISSUE THREAD

**Issue by cesar-luis-galli** [zeux/pugixml#488]
Hi.
I'm using pugi xml for a personal project (at least in this stage), which uses intensively xpath.
I have to say that performance of pugi's xpath implementation is more than satisfactory in general, but just today I've realized that fn:abs(number) is not implemented.  It doesn't seems to be a complex function to implement, and is part of the standard functions of xpath defined by W3Schools' specification.

Is it possible to add as a new feature?

Best regards.

**Comment by tuananh** [comment]
i think he only implements xpath 1.0 specs. `abs()` is from XPath 2.0 (XSLT 2.0) specs.

it's easy but maybe he doesn't want to commit to implementing the whole 2.0 specs

**Comment by zeux** [comment]
Yeah this is intentional because `abs` isn't part of XPath 2.0. pugixml only implements XPath 1.0.

XPath 2.0 is way larger than XPath 1.0 and way more complex; implementing it is completely outside of the scope. While it's of course possible to add selected functions from 2.0 to pugixml, it's unclear how you draw the boundary between the subset that's reasonable vs full implementation.
