### ISSUE TITLE
comment auto indentation problem

### ISSUE THREAD

**Issue by babchol** [zeux/pugixml#52]
I want to put some comments right after some node in one line.
(ex)
 <subnode />     

However, pugixml always move comments into new line after saving contents.
(ex)
 <subnode />

pugi::xml_document doc;

Here is full source code.

	doc.load_string(L"<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n\r\n<node>\r\n\t<subnode />      \r\n</node>", 
		pugi::parse_default | pugi::parse_declaration | pugi::parse_doctype | pugi::parse_comments);

	doc.save_file(L"test.xml", L"\t", pugi::format_default | pugi::format_write_bom, pugi::encoding_utf16);

Is there any option capable of putting comments in the same line with some nodes?

**Comment by zeux** [comment]
You can disable auto-indent altogether by using pugi::format_raw, I guess. You'd have to insert PCDATA nodes to restore the indentation, of course.

If you just want to keep the original formatting, parsing the file with pugi::parse_ws_pcdata flag will keep the whitespace PCDATA nodes in the document; save_file will use them so that the indentation is preserved. The problem with this approach is that it may complicate the parsing of the document since there could be cases where you'd have to ignore them.

If you want to reformat using some special rules, your only options are inserting PCDATA nodes and using format_raw or just writing your own recursive formatter with special code for comments, I'm afraid.
