### ISSUE TITLE
INTERFACE_LIBRARY targets may only have whitelisted properties.

### ISSUE THREAD

**Issue by Finkman** [zeux/pugixml#534]
## The Setup

I use `pugixml (v1.13)` as an in-source library in folder `lib/pugixml`. The entire project is build with `BUILD_SHARED_LIBS=OFF`.

I am using cmake 3.18.2

## The Error

When I configure the project, I receive the error from cmake:

```
CMake Error at libs/pugixml/CMakeLists.txt:155 (add_library):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "INCLUDE_DIRECTORIES" is not allowed.
```

> **NOTE:** This also happens with current master ( 1dc3266fffdb1f37961172c5c96af2f7e6132789 )

## Expectation

cmake configure step executes without an error.

**Comment by zeux** [comment]
Given the amount of issues we've had last time with aliases etc. I'm very worried about merging *any* changes that change the existing alias structure at all. See issues linked from https://github.com/zeux/pugixml/issues/392.

Is this error specific to CMake 3.18?

Looking at the diff from 1.11.4, I'm not sure I undestand if anything changed since then to produce this error. Notably, CMakeLists.txt does *not* add include directories for pugixml target itself. Does your CMake setup interact with pugixml targets in any way besides just including the pugixml folder?

**Comment by Finkman** [comment]
This  also happend with CMake 2.25.
But,... my guess was kind of misleading. The issue was caused by an odd mistake on my side where two different pugixml-folders interfere each other. With this, the second was trying to set properties on the target that has been defined before.
Sorry for the noise.
