### ISSUE TITLE
Change include dirs convention 

### ISSUE THREAD

**Issue by LukeCz** [zeux/pugixml#55]
Hi,

Could you change build scripts so pugixml.hpp and pugiconfig.hpp are not directly in include but in include/pugixml? This would also require changing in pugixml.hpp:
#include "pugiconfig.hpp" to #include "pugixml/pugiconfig.hpp"

This way my project can write #include <pugixml/pugixml.hpp> instead of #include <pugixml.hpp>.
This is following the Boost convention of always have library name in include.

**Comment by zeux** [comment]
> This would also require changing in pugixml.hpp:
> #include "pugiconfig.hpp" to #include "pugixml/pugiconfig.hpp"

No. This is extremely bad practice. (yes, I know Boost and other libraries use it. It is very painful for small libraries; for Boost you pretty much give up and add Boost to include folder).

Users need to be able to put the library files anywhere and include them and have everything work. pugixml explicitly requires zero configuration - no custom defines, no custom includes, etc. etc. Your project may have an arbitrary convention for putting third-party libraries into the source tree, for setting include paths, etc. - pugixml will work with anything *because* it does not impose a folder structure.

Regarding changing the build scripts (I'm assuming you mean CMake?), https://github.com/zeux/pugixml/issues/44#issuecomment-116093127.

**Comment by zeux** [comment]
If you want to follow Boost convention, feel free to put pugixml files in something like thirdparty/pugixml/ folder and setup include path to thirdparty so that you can use "pugixml/pugixml.hpp" include, although this even looks redundant.

Note that Boost is happy to give you &lt;boost/thread.hpp&gt; instead of &lt;boost/thread/component.hpp&gt;, you only need to specify the library name in the path for fine-grained includes.

**Comment by LukeCz** [comment]
Unfortunatelly the workaround you proposed will not work because of 
pugixml.hpp:#include "pugiconfig.hpp"

If I put pugixml.hpp in thirdparty/pugixml/ and include it at pugixml/pugixml.hpp then pugiconfig.hpp will not be found. This will why all Boost headers have boost/ in all includes and this is why I proposed this change.
Also the comment regarding thread.hpp does not apply here. Both versions of thread.hpp have boost/ prefix. This way you know that thread.hpp belongs to Boost library (in addition to thread library).

**Comment by zeux** [comment]
What compiler have you tried this on and what message are you getting?

Here's clang:

    #include "src/pugixml.hpp"
    #include <src/pugixml.hpp>

Compiles fine with:

    c++ test.cpp -I ~/pugixml

**Comment by LukeCz** [comment]
Hi, I was able to configure makefile to install pugixml the way you proposed and it works now. Thanks.
