### ISSUE TITLE
Conflicting documentation for multiple top-level element nodes

### ISSUE THREAD

**Issue by aschult5** [zeux/pugixml#554]
`parse_fragment` [documentation](https://pugixml.org/docs/manual.html#loading.options) states that when **on**, it
> ... permits multiple top-level element nodes

This implies that when it's **off**, multiple top-level element nodes are disallowed.

However, the [Conformance section](https://pugixml.org/docs/manual.html#loading.w3c) states
> Document can contain multiple top-level element nodes.

I'm observing that multiple top-level element nodes are always allowed. Perhaps the `parse_fragment` documentation should be clarified.

**Comment by zeux** [comment]
Yeah this is somewhat intentional but perhaps can be clarified somehow?

`parse_fragment` guarantees a few things, including (but not limited to) ability to have multiple top-level element nodes.

When you don't specify the flag, you can have multiple top-level element nodes but other properties of fragment parsing (such as top-level text node preservation) do not hold. This is a compatibility measure - when pugixml shipped many years ago, it allowed multiple top-level nodes but didn't have a way to indicate that this was required as `parse_fragment` did not exist.

So the recommendation in general would be to still use `parse_fragment` if the application needs multiple top-level nodes, even though in absence of this option it still works.

**Comment by aschult5** [comment]
Thanks for the explanation. A sentence explaining that the inverse doesn't hold when `parse_fragment` is off may save folks some time. But as it stands I agree that it's logically correct, just a bit misleading without the context of the conformance section.
