### ISSUE TITLE
xml_node_iterator should satisfy at least std::input_or_output_iterator concept

### ISSUE THREAD

**Issue by lazan** [zeux/pugixml#572]
To be a good iterator citizen, `xml_node_iterator` should satisfy `std::input_or_output_iterator` concept. 
Some _range/algorithm-abstractions_ forces iterator-like types to satisfy `std::input_or_output_iterator` (at least), which make it hard/impossible to use `xml_node_iterator` directly. 

For `xml_node_iterator` to satisfy `std::input_or_output_iterator` it needs to return non const reference for the pre-increment operator.
Naively, this change should not break ABI.

**Comment by zeux** [comment]
Yeah this is unfortunate... same problem exists in operator-- and ++/-- operators for other iterators. On Windows I think this would be an ABI breaking change as return type is part of mangled name but on other systems it's not; given that ABI compatibility is more of a problem on Linux due to packaged distributions this is probably fairly safe to fix.

**Comment by zeux** [comment]
Wait :)

This already happened 2 years ago. https://github.com/zeux/pugixml/commit/ef257796dbe00ef465cae2fca450ab16c23e2f63

It has been part of two releases since (v1.12 and v1.13). It appears that you're using pugixml 1.7; please upgrade to latest pugixml version.

**Comment by lazan** [comment]
What the... "I did check the latest version"... Well, apparently not, sorry...
