### ISSUE TITLE
qt string

### ISSUE THREAD

**Issue by balmerdx** [zeux/pugixml#60]
Собственно говоря такой вопрос. Пишу в последнее время на QT, но все равно использую pugixml.   Все отлично, но работа с QString неудобна. Если встрою поддержку в необходимые места и пришлю pull request - это имеет смысл?

**Comment by zeux** [comment]
(for people who don't read Russian, the question/proposal is to enhance pugixml to make it easier to work with QString)

There are several ways in that you could change pugixml to make it easier to work with different Qt types - examples include https://github.com/Textalk/pugixml/commit/be9050c341f1305b90be945b3d4a20d458fa44d3 / https://github.com/Textalk/pugixml/commit/96799dfc117f584633dc4992cc558313ee881a1b and extra support for getting/setting node/attribute data with QString (I had a suggested patch at some point for something like that but I can't really find it).

In general I don't really see this as something that needs to be in pugixml core. I'd prefer a separate header - e.g. similar to contrib/foreach.hpp there could be contrib/qt.hpp - that somehow extended the API or provided conversion helpers so that you could use Qt types.

My understanding is that getting node data as QString is already transparent enough since QString provides a ctor from const char* - so the only inconvenience is in passing data to pugixml, where you have to do .toStdString().c_str() for all arguments. This can probably be wrapped in a helper class or a macro somehow.

**Comment by ybungalobill** [comment]
Note that by default toStdString() returns ISO-8859-1, not the system codepage, nor UTF-8 expected by pugixml in narrow compilation. The correct way is to use .toUtf8().data().

**Comment by zeux** [comment]
I was looking at Qt 5.5 documentation when I wrote the code above:

> Returns a std::string object with the data contained in this QString. The Unicode data is converted into 8-bit characters using the toUtf8() function.

Qt 4 uses toAscii indeed...

**Comment by ybungalobill** [comment]
Hmm, you are right. Didn't know, and that's a good Qt change!

**Comment by zeux** [comment]
Closing this for now; as mentioned above, happy to accept a separate header (e.g. contrib/qt.hpp) that somehow makes Qt interop easier.
