### ISSUE TITLE
Question: I have made my own case insensitive version, is that ok?

### ISSUE THREAD

**Issue by mr-phazer** [zeux/pugixml#609]
To author: Thanks for an amazing product, I have used for everything for 3-4 years now :)
I have eited the and have made a "version" og PUGI-XML has has `child_no_case()` and `atrribute_no_case()` added methods, 

```
PUGI_IMPL_FN xml_node xml_node::child_no_case(const char_t* name_) const
{
	if (!_root) return xml_node();

	for (xml_node_struct* i = _root->first_child; i; i = i->next_sibling)
	{
		const char_t* iname = i->name;			
		if (iname &&  toUpper(name_) == toUpper(iname))			
			return xml_node(i);
	}

	return xml_node();
}

```
I am also thinking about changing `impl::strequel()` conditionally, is this okay within the license?
I saw that some of your users really wanted this, and in many cases it is really needed,

**Comment by zeux** [comment]
You can of course patch pugixml for use in your projects however you want. As noted in https://github.com/zeux/pugixml/issues/26#issuecomment-77272409 this addition is not a good fit for pugixml for a number of reasons (one of them is that the correct case insensitive comparison is very difficult to implement; your function only works correctly with ASCII and will have issues when invoked on UTF-8 data depending on locale).

Instead of patching pugixml, which would need to be merged with any future updates, I would recommend using a separate function as noted in the linked comment: you can implement `child_no_case` using public pugixml API and put that in a separate header that you use in your application(s).

Finally, please use GitHub Discussions for questions in the future.

**Comment by mr-phazer** [comment]
Ok, sorry I posted here.
