### ISSUE TITLE
call function xml_node::empty() always return false in anyway

### ISSUE THREAD

**Issue by yuzu-ogura** [zeux/pugixml#614]
VERSION : pugixml 1.14
Test Code:
`std::cout << "Hello, World!" << std::endl;`
`pugi::xml_document doc;`
`std::cout << std::boolalpha << doc.empty() << std::endl;`

Console Output:
![image](https://github.com/zeux/pugixml/assets/166282486/beccffb8-48d2-4c43-8048-2b134ef52179)

I think it should return true

**Comment by zeux** [comment]
`empty()` is documented in the manual:

https://pugixml.org/docs/manual.html#xml_node::empty

I assume you think it checks if the node has children. It doesn't - it checks if the node is a null node (a different name would have been better perhaps, but this choice was made >15 years ago...).

As a consequence, document is, of course, never "empty" - because empty is synonymous with `.type() == pugi::node_null`, and for a document `.type() == pugi::node_document`.

**Comment by zeux** [comment]
If you want to check if the node has children you can do it like this:

```
node.children().empty()
```
