### ISSUE TITLE
Read-only access to xml_document

### ISSUE THREAD

**Issue by c-robert** [zeux/pugixml#62]
I'd like to have a shared xml_document but only allow read-only access to the data for the shared instances. All would be accessing the same document, I just don't want to allow editing the document by any other object.

What is the best approach for providing read-only access to the document?

I've considered adding a read-only attribute on the document itself which would have to be propagated to all nodes.

I've also looked at implementing const versions of xml_node, xml_attribute, xml_text, xpath_node, xpath_node_set, xml_node_iterator, and xml_attribute_iterator which would inherit privately from the non-const class and then expose only the methods that are const and convert return types to the const version.

Which of these two would be best, or is there something else I could do?

**Comment by zeux** [comment]
You're basically looking for additional verification - either compile-time (by making type-safe const-correct interfaces) or run-time (by adding assertions that check the read-only flag), right?

**Comment by c-robert** [comment]
Yes, although my preference is at compile-time. I will be exploring that option soon, I'm just looking for any guidance on the most prudent path to accomplish this.

**Comment by zeux** [comment]
In terms of the amount of changes to existing code assertions are easiest. In any member function of xml_node, you can just write

    assert(!_root || !impl::get_document(_root)->readonly);

And then add a readonly bool to xml_document_struct and accessors to xml_document.

The only way to do a compile-time verification that I see is as you suggested - add xml_const_node etc. I would not necessarily use private inheritance - since you have to implement all public methods by delegating them to the base implementation and converting types, I'd just write a separate class and implement members like this

   xml_const_node child(const char_t* name) { return xml_const_node(xml_node(_root).child(name).internal_object()); }

Of course this is kinda cumbersome. However, you can do it completely externally without changing pugixml source so that this will not break with pugixml updates.

**Comment by c-robert** [comment]
Thanks! I'll pursue the compile time approach with a separate file as you suggested.
