### ISSUE TITLE
nullptr and noexcept

### ISSUE THREAD

**Issue by davidhunter22** [zeux/pugixml#63]
It may be better to use nullprt and noexcept thather then a '0' and throw(). You can always #47 # define nullptr and noexcept to be other things on compilers that don't support them.

**Comment by zeux** [comment]
Is there any benefit in using nullptr and noexcept instead of 0 and throw() on compilers that do support them?

pugixml only really uses throw() in xpath_exception::what() override (and only because some compilers emit warnings if you don't specify that).

**Comment by davidhunter22** [comment]
My understanding is that exception specifiers such as throw() are deprecated and that noexcept can result in more performant code. See https://akrzemi1.wordpress.com/2011/06/10/using-noexcept/ for one post on the topic. 
nullptr is even more clear cut. 0 is not a pointer it is an integer, see here http://blogs.msdn.com/b/devschool/archive/2013/07/31/null-nullptr-dull-certainly-not-new-c-11-stuff.aspx for one discussion.
I would suggest using nullptr and noexcept and make them defines to 0 and empty if you need to support old compilers. You can do "#define noexcept throw()" as well although I'm a bit surprised about your comment about compiler warnings.

**Comment by zeux** [comment]
Regarding throw(), exception specifications will be removed from C++17, however throw() specification will still remain as an alias for noexcept(true). Any performance gains do not really matter in the case where pugixml uses it. Not sure why you're surprised about my comment - some compilers warn on difference in exception specification between virtual function overrides.

Regarding nullptr, in general the policy towards C++11 features in pugixml - and in my mind the only policy that makes sense for libraries that do not *require* C++11 - is to use any C++1x features if they improve user experience or performance and stay away from them otherwise. I am well aware of the differences between 0 and nullptr and frankly quite a bit annoyed by now for people linking unrelated "explanations" of C++11 features.

In any case where nullptr changes the compilation result defining nullptr to 0 on compilers that don't support C++11 will... change the compilation result! Like, the code will not compile on older compilers if pugixml ever has something similar to the example from that MSDN article. In cases where both nullptr and 0 are valid using 0 is compatible with pre-C++11 compilers and results in the same code being generated.
