### ISSUE TITLE
opening file with long path on a network fails

### ISSUE THREAD

**Issue by st80rules** [zeux/pugixml#637]
Using version 1.14, if I try to import a file on a network with a long path length, it fails with status_file_not_found. Note that the path length is around 280 characters.

File notation is 

\\\ip_address\some\very\long\path\myfile.xml

If I move the file to a shorter path on the same network, it loads correctly.

I tried prefixing the file name with this:

\\\\?\

and it didn't help.

**Comment by brandl-muc** [comment]
Due to the mentioned prefix you are in windows.
Ich Ou check the docs regarding [Maximum Path Length Limitation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) you'll find this:

To specify such a path using UNC, use the "\\?\UNC\" prefix. For example, "\\?\UNC\server\share", where "server" is the name of the computer and "share" is the name of the shared folder.

**Comment by st80rules** [comment]
The form with the UNC keyword did work. Thanks!
