### ISSUE TITLE
as_int default value ignored if the attribute exists

### ISSUE THREAD

**Issue by ephraimo** [zeux/pugixml#80]
When using as_int(1) on attributes such as:
Threshold=""
or:
Threshold="non-numeric"

The return value is 0 instead of the default 1 as expected according to the manual: http://pugixml.org/docs/manual.html#access.attrdata

The same holds true for the other numeric attribute accessors.

**Comment by zeux** [comment]
The non-numeric case is working as documented (result is undefined). Issue #15 tracks improvements in this area.

The empty case is indeed not working as documented. I'm currently intending to change documentation since I don't see a good reason for difference in behavior between threshold="" and threshold="a".
