### ISSUE TITLE
Convert 0 to nullptr

### ISSUE THREAD

**Issue by mfeemster** [zeux/pugixml#91]
If you compile pugixml with this option enabled in gcc: -Wzero-as-null-pointer-constant

There are a ton of warnings. You should probably move to C++11 style and use nullptr instead of 0 for pointers.

Thanks.

**Comment by zeux** [comment]
Why do you need to compile pugixml with Wzero-as-null-pointer-constant?

**Comment by mfeemster** [comment]
I don't need to, it's just that I usually have that option turned on. It's really just a matter if you want to have the code base be fully C++11 compliant. If not, disregard this issue.

**Comment by zeux** [comment]
As far as I know, being fully C++11 compliant does not require using nullptr instead of 0. The gcc warning is more like a "style" warning, similar to some other warnings that aren't unambiguously good...

There are two small practical issues with using nullptr in pugixml:

- pugixml is *not* a C++11 codebase - it supports lots of compilers that predate C++11. So just using nullptr will break compatibility for a lot of users. This should be fixable by defining nullptr as 0 if compiler does not support nullptr natively, hopefully.

- The development environment I use does not support the warning, so there's some chance of breaking this from time to time. This seems to be fixable by relying on CI results though, since Travis CI uses gcc-4.8.4 which should have this warning.

**Comment by mfeemster** [comment]
You're correct, it's just stylistic and doesn't add anything. I'll close this issue. Thanks.
